version: 2.1
jobs:
  build: &build
    docker:
      - image: tarampampam/node:13-alpine
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: '.'
      - run:
          name: 'Build artifacts'
          command: |
            node --version
            npm --version
            yarn install
            yarn build:develop
      - persist_to_workspace:
          root: '.'
          paths:
            - '.'
  build_prod:
    <<: *build
  build_develop:
    <<: *build
  build_goerly:
    <<: *build
  upload: &upload
    docker:
      - image: bigbadalien/awscli-node-kops-kubectl:0.3
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: '.'
      - run:
          name: 'Upload artifacts'
          command: |
            pwd
            echo "Uploading assets to $DOMAIN"
            aws s3 cp ./build s3://$DOMAIN/ --acl bucket-owner-full-control --recursive --cache-control "public,max-age=600,s-maxage=3600"
            echo "Invalidating CDN network"
            INVALIDATION_ID=`aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*' | jq -r '.Invalidation.Id'`
            echo "Invalidation ID is $INVALIDATION_ID"
            echo "CDN Invalidation request is sent."
  upload_prody:
    <<: *upload
  upload_develop:
    <<: *upload
  upload_goerly:
    <<: *upload

workflows:
  version: 2.1
  stkr_web3:
    jobs:
      - hold_build_prod:
          type: approval
      - build_prod:
          context: stkr_build_prod
          requires:
            - hold_build_prod
      - upload_prod:
          context:
            - cicd
            - stkr_build_prod
          requires:
            - build_prod

      - hold_build_develop:
          type: approval
      - build_develop:
          context: stkr_build_develop
          requires:
            - hold_build_develop
      - upload_develop:
          context:
            - cicd
            - stkr_build_develop
          requires:
            - build_develop

      - hold_build_goerli:
          type: approval
      - build_goerli:
          context: stkr_build_goerli
          requires:
            - hold_build_goerli
      - upload_goerli:
          context:
            - cicd
            - stkr_build_goerli
          requires:
            - build_goerli
